package com.neu.edu.pojo;

import java.io.File;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
	


@Entity
@Table(name="Product")
public class Product {
	//id automatic generated by hibernate
	@Id
    @GeneratedValue 
    @Column(name="productId", unique = true, nullable = false)
	private long productId;
	
	@Column(name="productName")
	private String productName;
	
	@Column(name="productDescription")
	private String productDescription;
	
	@Column(name="productImage")
	private String productImage;
	
	@Column(name="productQuantity")
	private String productQuantity;
	
	@Column(name="productPrice")
	private String productPrice;
	
	@Column(name="categoryId")
	private long categoryId;
	
	@Column(name="categoryName")
    private String categoryName;
	
	@Column(name="supplierUserName")
	private String supplierUserName;
	
	@Column(name="supplierCompany")
	private String supplierCompany;
	
	
	
	
	// getter setters required
	public long getProductId() {
		return productId;
	}
	
	
	public void setProductId(long productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}

	
	
	public String getProductImage() {
		return productImage;
	}


	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}


	public String getProductDescription() {
		return productDescription;
	}
	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	
	
	/*
	
	@Column(name="supplierId")
	public String supplierId;
	
	public Set<Supplier> getSupplier() {
		return supplier;
	}
	public void setSupplier(Set<Supplier> supplier) {
		this.supplier = supplier;
	}

*/
	@ManyToMany(fetch=FetchType.LAZY, mappedBy = "products")
    private Set<Supplier> suppliers = new HashSet<Supplier>();
	
	@ManyToMany(fetch=FetchType.LAZY, mappedBy = "productsCart")
    private Set<User> users = new HashSet<User>();
	
	 public Set<Supplier> getSuppliers() {
		return suppliers;
	}


	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}


	public String getCategoryName() {
		return categoryName;
	}



	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}



	



	public Set<User> getUsers() {
		return users;
	}


	public void setUsers(Set<User> users) {
		this.users = users;
	}


	public long getCategoryId() {
		return categoryId;
	}


	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}


	public Category getCategory() {
		return category;
	}


	public void setCategory(Category category) {
		this.category = category;
	}

	
	
	public String getProductQuantity() {
		return productQuantity;
	}


	public void setProductQuantity(String productQuantity) {
		this.productQuantity = productQuantity;
	}


	public String getProductPrice() {
		return productPrice;
	}


	public void setProductPrice(String productPrice) {
		this.productPrice = productPrice;
	}




	public String getSupplierUserName() {
		return supplierUserName;
	}


	public void setSupplierUserName(String supplierUserName) {
		this.supplierUserName = supplierUserName;
	}


	public String getSupplierCompany() {
		return supplierCompany;
	}


	public void setSupplierCompany(String supplierCompany) {
		this.supplierCompany = supplierCompany;
	}



	@ManyToOne
    @JoinColumn(name="categoryId", insertable = false, updatable = false)
    private Category category;
	
	public Product(){}
	
	public Product( String productName, String productImage, String productDescription,String productPrice,String productQuantity, long categoryId, String categoryName){
		this.productImage = productImage;
		
		this.productName = productName;
		this.productDescription = productDescription;
		this.productPrice = productPrice;
		this.productQuantity = productQuantity;
		this.categoryName = categoryName;
		//this.categoryId = category.getCategoryId();
		this.categoryId = categoryId;
	}
	
}
